const assert=require('node:assert/strict');const{chromium}=require('playwright');
(async()=>{
const b=await chromium.launch({executablePath:process.env.CHROME_BIN||undefined,args:['--no-sandbox']});
const p=await b.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});
await p.goto(process.env.MOTION_TEST_URL||'http://localhost:3212/portfolio');
await p.waitForFunction(()=>document.querySelector('footer')||document.body.innerText.includes('FIND ME'));
assert.equal(await p.locator('.photos,.photo,.photo-caption').count(),0);
assert.equal(await p.locator('.pin-spacer').count(),0);
assert.equal(await p.locator('html').evaluate(e=>getComputedStyle(e).scrollBehavior),'auto');
assert.equal(await p.locator('html.lenis').count(),0);
await p.emulateMedia({reducedMotion:'no-preference'});
await p.waitForFunction(()=>document.documentElement.classList.contains('lenis'));
assert.equal(await p.locator('.photos,.photo,.photo-caption,.pin-spacer').count(),0);
await p.emulateMedia({reducedMotion:'reduce'});
await p.waitForFunction(()=>!document.documentElement.classList.contains('lenis'));
await p.setViewportSize({width:390,height:844});
await p.getByRole('button',{name:'Open menu',exact:true}).click();
await p.keyboard.press('Escape');
assert.equal(await p.getByRole('button',{name:'Open menu',exact:true}).getAttribute('aria-expanded'),'false');
console.log('photo section absent, reduced noLenis/noPin, preference cleanup and mobile Escape pass');
await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
